apiVersion: v1
kind: Pod
metadata:
  labels:
    kiwi-snyk-service-a.service: service-a
  name: service-a
spec:
  containers:
    - image: kiwi-snyk-service-a:latest
      name: service-a
      ports:
        - containerPort: 5000
      livenessProbe:
        httpGet:
          path: /
          port: 5000
          httpHeaders:
          - name: Custom-Header
            value: Health Probe
        initialDelaySeconds: 3
        periodSeconds: 3
      resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  restartPolicy: OnFailure
